// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Index(Props) {
  React.useState(function () {
        return false;
      });
  return React.createElement("div", {
              className: "w-full h-screen overflow-hidden font-space"
            });
}

var make = Index;

var $$default = Index;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
