// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var App$MyBlog = require("../src/components/app.bs.js");
var Page$MyBlog = require("../src/components/page.bs.js");

function Index(Props) {
  React.useState(function () {
        return false;
      });
  return React.createElement(Page$MyBlog.make, {
              children: React.createElement(App$MyBlog.make, {})
            });
}

var make = Index;

var $$default = Index;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
