// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");

var testStyle = Curry._1(Css.style, {
      hd: Css.color(Css.pink),
      tl: /* [] */0
    });

exports.testStyle = testStyle;
/* testStyle Not a pure module */
