// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var GoodbyeStyles$MyBlog = require("./GoodbyeStyles.bs.js");

function Goodbye(Props) {
  return React.createElement("div", {
              className: Curry._1(Css.merge, {
                    hd: GoodbyeStyles$MyBlog.testStyle,
                    tl: {
                      hd: "text-6xl",
                      tl: /* [] */0
                    }
                  })
            }, "Goodbye  thomas");
}

var make = Goodbye;

var $$default = Goodbye;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Css Not a pure module */
