// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Landing$MyBlog = require("./landing.bs.js");
var LoadingScreen$MyBlog = require("./loadingScreen.bs.js");

function App(Props) {
  var match = React.useState(function () {
        return /* Landing */0;
      });
  var setView = match[1];
  var view = match[0];
  var onSubmit = function (e) {
    e.preventDefault();
    Curry._1(setView, (function (param) {
            return /* Loading */2;
          }));
    console.log("HIII");
    
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: view !== 0 ? "hidden" : ""
                }, React.createElement(Landing$MyBlog.make, {
                      onSubmit: onSubmit
                    })), React.createElement("div", {
                  className: view >= 2 ? "" : "hidden"
                }, React.createElement(LoadingScreen$MyBlog.make, {})), React.createElement("div", {
                  className: view !== 1 ? "hidden" : ""
                }));
}

var make = App;

var $$default = App;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
