// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Call(Props) {
  return React.createElement("div", {
              className: "text-primary-100"
            }, "");
}

var make = Call;

var $$default = Call;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
