// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function CheckButton(Props) {
  var interestOpt = Props.interest;
  var interest = interestOpt !== undefined ? interestOpt : "hello";
  var match = React.useState(function () {
        return false;
      });
  var setIsChecked = match[1];
  var isChecked = match[0];
  return React.createElement("div", {
              className: "cursor-pointer " + (
                isChecked ? "go" : "bg-blue-200"
              ),
              onClick: (function (param) {
                  return Curry._1(setIsChecked, (function (param) {
                                return !isChecked;
                              }));
                })
            }, interest);
}

var make = CheckButton;

var $$default = CheckButton;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
