// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Header(Props) {
  return React.createElement("div", {
              className: "text-primary-100"
            }, "I'm a header look at me");
}

var make = Header;

var $$default = Header;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
