// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Header(Props) {
  return React.createElement("div", {
              className: "w-full py-12 text-lightgray flex flex-col items-center bg-secondary-500 justify-center"
            }, React.createElement("div", {
                  className: "inline-block text-5xl"
                }, "Dinner for 12 Strangers"), React.createElement("div", {
                  className: "inline-block"
                }, "Come and Eat with Other People!"));
}

var make = Header;

var $$default = Header;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
