// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Hello(Props) {
  return React.createElement("div", {
              className: "text-primary-100"
            }, "Hello thomas");
}

var make = Hello;

var $$default = Hello;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
