// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Header$MyBlog = require("./header.bs.js");
var CheckButton$MyBlog = require("./checkButton.bs.js");

function Landing(Props) {
  var onSubmit = Props.onSubmit;
  var match = React.useState(function () {
        return "";
      });
  var setUserName = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement(Header$MyBlog.make, {}), React.createElement("form", {
                  className: "flex flex-col justify-center w-full",
                  onSubmit: onSubmit
                }, React.createElement("div", {
                      className: "mx-auto"
                    }, React.createElement("label", {
                          className: "block text-center"
                        }, "What is your name?"), React.createElement("input", {
                          name: "name",
                          type: "text",
                          value: match[0],
                          onChange: (function (target) {
                              return Curry._1(setUserName, target.target.value);
                            })
                        })), React.createElement("div", {
                      className: "text-center"
                    }, React.createElement("div", undefined, "What are your interests?"), React.createElement("div", {
                          className: "inline-grid grid-cols-2 gap-3 w-24 justify-center"
                        }, React.createElement(CheckButton$MyBlog.make, {}), React.createElement(CheckButton$MyBlog.make, {}), React.createElement(CheckButton$MyBlog.make, {}))), React.createElement("button", {
                      className: "m-auto bg-green-200",
                      type: "submit"
                    }, "submit")));
}

var make = Landing;

var $$default = Landing;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
