// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Loading = require("src/js/Loading").default;

function LoadingScreen(Props) {
  return React.createElement("div", {
              className: "text-center"
            }, React.createElement("div", {
                  className: "animate-bounce"
                }, "Please wait"), React.createElement("div", {
                  className: "w-48 m-auto"
                }, React.createElement(Loading, {})));
}

var make = LoadingScreen;

var $$default = LoadingScreen;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
